### ISSUE TITLE
Module keeps asking to update manifest in endless loop

### ISSUE THREAD

**Issue by AcidAde-7726** [hitcherland/foundryvtt-macro-to-del#1]
![image](https://user-images.githubusercontent.com/83780107/123435810-3584d400-d58b-11eb-84fc-01dd2ff32adf.png)

1. Update Module
2. Dialog Displays
3. Click Yes
4. Refresh Modules Page
5. Click update on module
6. Dialog appears ....

**Comment by hitcherland** [comment]
Thanks for posting this! I'm guessing your installing this on 0.8.x, as this wasn't a problem with 0.7.x. I can't guarantee v0.1.2 will work, but I've adjusted the package manifest so this shouldn't show up.

**Comment by AcidAde-7726** [comment]
Cool - thanks - yes it was with 0.8.8 and I think 0.8.7 did it too.
