### ISSUE TITLE
Constantly seeing update Manifest

### ISSUE THREAD

**Issue by HippyCraig** [hitcherland/foundryvtt-macro-to-del#5]
Every time I run the update moduals function in Foundry even though its updated I still see this every time

![image](https://user-images.githubusercontent.com/17074456/154121515-9ccc103a-3400-4079-b9c2-9d39de814246.png)

Just wanted to bring it to your attention, none of the other mods are doing this.

**Comment by hitcherland** [comment]
I think I've fixed that, sorry for the annoyance!

**Comment by HippyCraig** [comment]
Cool thanks, it wasnt annoying I just wanted to bring it to your attention, thanks for teh quick response :)
